spring:          #表示该配置直接为Spring容器负责处理
　　datasource:
  　　driver-class-name: com.mysql.cj.jdbc.Driver      #配置MySQL的驱动程序类
  　　url: jdbc:mysql://localhost:127.0.0.1/projectdesigner?serverTimezone=GMT%2B8
  　　username: root
  　　password: root
mybatis:
  mapper-locations:
    classpath:mapping/*.xml:

ftpHost :
  192.168.0.3
ftpPort :
  21
ftpUsername :
  wubo
ftpPassword :
  wb1996102288
ftpPath :
  /front

localPath :
    E:/frontftp

threadNum :
   10
